name: Deploy to S3

on:
  push:
    branches:
      - main  # or the branch you use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Sync site folder to S3
        run: aws s3 sync ./site s3://crc.awsportfolio.jayfrench.cloud --delete
        
#     - name: Invalidate CloudFront Cache
#       run: aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"
